-define(DEFAULT_STA_SSID, <<"esl-iot">>).
-define(DEFAULT_STA_PSK, <<"Letitcrash">>).
-define(DEFAULT_NTP_HOST, "pool.ntp.org").
-define(DEFAULT_GW_HOST, {10, 10, 42, 180}).
-define(DEFAULT_GW_DATA_PORT, 9999).
-define(DEFAULT_GW_COMM_PORT, 9998).
-define(DEFAULT_GW_HANDLER, c3card_gateway_command).
-define(DEFAULT_SENSORS, [{aht20, start_link, []}, {bme280, start, [{address, 16#77}]}]).
